name: Deploy on DigitalOcean Personal VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/Englishom
            git pull origin master
            # Add your build/restart commands here
            # For example:
            sudo npm install
            sudo npm run build
            sudo pm2 restart main
